apiVersion: v1
  
kind: Pod
  
metadata:
  
  name: test-pod
  
spec:
  
  containers:
  
    - name: test-container
  
      image: busybox
  
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
  
      envFrom:
  
      - configMapRef:
  
          name: test-cm
  
  restartPolicy: Never
